In [6]:
import numpy as np

In [28]:
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
B = [[1,2,3],
     [4,5,6],
     [7,8,9]]
A = np.array(A)
B = np.array(B)

In [29]:
def msum(A,B):
    if(A.shape == B.shape):
        C  = np.zeros(A.shape)
        for i in range(0,A.shape[0]):
            for j in range(0,A.shape[0]):
                C[i][j] = A[i][j] + B[i][j]
    return C
        

In [30]:
print(msum(A,B))

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [32]:
def mmult(A,B):
    if(A.shape[1] == B.shape[0]):
        C = np.zeros([A.shape[0],B.shape[1]]);
        
        for i in range(0,A.shape[0]):
            for j in range(0,B.shape[1]):
                
                for k in range(0,A.shape[1]):
                    C[i][j] += A[i,k]*B[k,j]
        return C
            

In [33]:
print(mmult(A,B))

[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]


In [44]:
def mtrasp(A):
    C = np.zeros(A.shape)
    for i in range(0,C.shape[0]):
        for j in range(0,C.shape[1]):
            C[j][i] = A[i][j]
    return C

In [45]:
print(mtrasp(A))

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [42]:
def traza(A):
    if(A.shape[0] == A.shape[1]):
        trz =  0
        for i in range(0,A.shape[0]):
            trz += A[i][i]
    return trz
        

In [43]:
print(traza(A))

15
