In [35]:
import numpy as np
import matplotlib.pyplot as plt

In [48]:
#puntos experimentales 
xL =[1.0,1.3,1.6,1.9,2.2]
yL = [0.7651977,0.6200860,0.4554022,0.2818186,0.1103623]

n = len(xL)

T =  np.zeros((n,n))
print(T)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [49]:
for i in range(0,n):
   for j in range(0,n):
       if i==j:
            T[i][j] = yL[j]
       else:
            continue

#print(T)            
#llenamos la matriz diagonal superior 
for  k in range(1, n):
    for i in range(0, n-1):
        for j in range(1,n):
            if(j!=i) and j==i+k:
                 T[i][j] = (T[i+1][j]-T[i][j-1])/(xL[j]-xL[i])

print(T)
                
x=1.6   
px = yL[0]

for i in range(1, n):
    prod = 1 
    for j in range(0,i):
        prod = prod*(x-xL[j])
    px = px + T[0][i]*prod
print(px)

[[ 0.7651977  -0.48370567 -0.10873389  0.0658784   0.0018251 ]
 [ 0.          0.620086   -0.548946   -0.04944333  0.06806852]
 [ 0.          0.          0.4554022  -0.578612    0.01181833]
 [ 0.          0.          0.          0.2818186  -0.571521  ]
 [ 0.          0.          0.          0.          0.1103623 ]]
0.4554022
