In [1]:
import numpy as np

In [16]:
#Carga de  coeficientes
coeff = np.loadtxt('coeff.dat')
print(coeff)
#Definición de limites internos de  integración

def  f(x,y):
    value = np.exp(y/x)
    return value
    
def c(x):
    value = x**3
    return value

def d(x):
    value = x**2
    return value

[[ 2.          0.57735027  1.        ]
 [ 2.         -0.57735027  1.        ]
 [ 3.          0.77459667  0.55555556]
 [ 3.          0.          0.88888889]
 [ 3.         -0.77459667  0.55555556]
 [ 4.          0.86113631  0.34785485]
 [ 4.          0.33998104  0.65214515]
 [ 4.         -0.33998104  0.65214515]
 [ 4.         -0.86113631  0.34785485]
 [ 5.          0.90617985  0.23692689]
 [ 5.          0.53846931  0.47862867]
 [ 5.          0.          0.56888889]
 [ 5.         -0.53846931  0.47862867]
 [ 5.         -0.90617985  0.23692689]]


In [19]:
def DoubleGauss(a,b,c,d,f,n,m):
    
    #Crea pesos(Wi,Wj) y raices(Zi,Zj)
    w_i=[]
    z_i=[]
    for i in range(0,coeff.shape[0]):
        if(n == int(coeff[i][0])):
            w_i.append(coeff[i][2])
            z_i.append(coeff[i][1])
            
    w_j=[]
    t_j=[]
    for j in range(0,coeff.shape[0]):
        if(m == int(coeff[j][0])):
            w_j.append(coeff[j][2])
            t_j.append(coeff[j][1])
    
    #Inicia integración
    sum_i = 0.0
    for i in range(0,n):
        x_i=0.5*((b-a)*z_i[i]+a+b)  #x(z_i)
        
        sum_j = 0.0
        for j in range(0,m):
            y_j=0.5*((d(x_i)-c(x_i))*t_j[j]+c(x_i)+d(x_i))
            sum_j += f(x_i,y_j)*w_i[i]*w_j[j]
        
        sum_i += sum_j*(d(x_i)-c(x_i))
        
    value = sum_i*0.25*(b-a)
    return value

In [20]:
print(DoubleGauss(0.1,0.5,c,d,f,5,5))

0.033305566114962486
